### ISSUE TITLE
Transaction history parsing result weird

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Gator.sol#62]
For some reason values are getting displayed like this. Should not be a comma separated list and just the value. 
The console I think displays the value so this should be an easy fix.

![image](https://user-images.githubusercontent.com/62024550/162047293-dc7e7186-0d7c-4eef-85bf-8eda6badf4f9.png)

**Comment by jdriscoll98** [comment]
oh it's probably splitting the string somewhere
