### ISSUE TITLE
Save code on refresh etc.

### ISSUE THREAD

**Issue by KyleStrout** [KyleStrout/Gator.sol#67]
Save the users code when they change/leave the page and have a reset button for resetting back to default code.
Probably can do this with local storage and should double check if they actually want to reset the code.

**Comment by jdriscoll98** [comment]
Yea we can do this through local storage. I can do it tomorrow or if u wanna try u can go for it. 

Just do something like 

`window.sessionStorage.setItem(key, value)`

and when the page loads we can do 

`window.sessionStorage.getItem(key, value)` 

setting it to that value if it exists or the default code if not.  I like the reset button too, could add use a dialog component from material UI to make a confirm / cancel button.
